### ISSUE TITLE
Sentinel 2 data and how it will work

### ISSUE THREAD

**Issue by dpoursanidis** [lanha/SupReME#1]
We are trying to use the matlab code using the SAFE data of Sentinel 2.
However the code is developed to use data based on the structure of APEX.
Do you have any manual on how to use it with actual Sentinel 2 data?

**Comment by lanha** [comment]
Hello. No, I don't have any such manual. You will need to read the data in matlab arrays. The script reads the variable Yim, a cell array that contains the multiple channels at different resolutions. After they've all been resized they are stored in the 3d matlab array Yinterp. Having that would be sufficient to run the demo.

**Comment by dzhong-hub** [comment]
I tried to use the matlab code to process a Sentinel-2 image (a complete tile). I encountered "out of memory" issue:
Out of memory. Type "help memory" for your options.
Error in createConvKernelSubspace (line 28)
        FBM2(:,:,i) = fft2(B(:,:,i));
Did you try to process a whole tile of Sentinel-2 image? Any comments are appreciated very much!

**Comment by lanha** [comment]
Hello, the MATLAB code is more intended to provide a demo. I never used it for a whole image, even though you could tile up the image in a similar manner to the python code and make it work.

**Comment by lanha** [comment]
No, I have never tried to process a whole tile at a time. You can do that by splitting up the image into smaller tiles.

**Comment by dzhong-hub** [comment]
Thank you for your response! I am trying to split the whole image into
small tiles.

**Comment by dzhong-hub** [comment]
Hi Charis,
I am trying to apply your two methods (SupReME and DSen2) for super
resolving Sentinel-2 images for our applications.
Any suggestions and updates for your software packages?
Thank you in advance,
Detang

By the way: I am working for a project from Canada Center for Remote
Sensing. Your support will be very much appreciated.

**Comment by lanha** [comment]
Thanks for your interest! I hope you find this work useful.
Unfortunately, I haven't worked on any updates since publishing this project. If you run into any issues you can let me know.
