### ISSUE TITLE
Subspace Dimension Selection

### ISSUE THREAD

**Issue by melanievt** [lanha/SupReME#3]
Dear Charis, 
In the "ms_fusion_apex.m" file, p is assigned as 7 with the following information - %7 just the number of bands with resolution 10. Wouldn't it be 4 for Sentinel-2 imagery? Is 7 just the optimum number for subspace dimension according to your research? I would be very glad, if you can provide further information about it. I might misinterpret it or miss something. 
Thanks in advance,
Mel

**Comment by lanha** [comment]
Hi Mel
Yes as you point out, it's the optimum number for subspace dimension based on heuristics and experimentation. I will correct the comment.
Cheers!

**Comment by melanievt** [comment]
Thank you!
